# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import communication.message_pb2 as message__pb2


class grpcServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.sendParameter = channel.unary_unary(
                '/message.grpcService/sendParameter',
                request_serializer=message__pb2.SelectedParameters.SerializeToString,
                response_deserializer=message__pb2.GlobalParameter.FromString,
                )
        self.sendSingleParameter = channel.unary_unary(
                '/message.grpcService/sendSingleParameter',
                request_serializer=message__pb2.SelectedParameter.SerializeToString,
                response_deserializer=message__pb2.EmptyResponse.FromString,
                )
        self.randomSample = channel.unary_unary(
                '/message.grpcService/randomSample',
                request_serializer=message__pb2.RequestRandomIndices.SerializeToString,
                response_deserializer=message__pb2.ResponseRandomIndices.FromString,
                )


class grpcServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def sendParameter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sendSingleParameter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def randomSample(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_grpcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'sendParameter': grpc.unary_unary_rpc_method_handler(
                    servicer.sendParameter,
                    request_deserializer=message__pb2.SelectedParameters.FromString,
                    response_serializer=message__pb2.GlobalParameter.SerializeToString,
            ),
            'sendSingleParameter': grpc.unary_unary_rpc_method_handler(
                    servicer.sendSingleParameter,
                    request_deserializer=message__pb2.SelectedParameter.FromString,
                    response_serializer=message__pb2.EmptyResponse.SerializeToString,
            ),
            'randomSample': grpc.unary_unary_rpc_method_handler(
                    servicer.randomSample,
                    request_deserializer=message__pb2.RequestRandomIndices.FromString,
                    response_serializer=message__pb2.ResponseRandomIndices.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'message.grpcService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class grpcService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def sendParameter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/message.grpcService/sendParameter',
            message__pb2.SelectedParameters.SerializeToString,
            message__pb2.GlobalParameter.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def sendSingleParameter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/message.grpcService/sendSingleParameter',
            message__pb2.SelectedParameter.SerializeToString,
            message__pb2.EmptyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def randomSample(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/message.grpcService/randomSample',
            message__pb2.RequestRandomIndices.SerializeToString,
            message__pb2.ResponseRandomIndices.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
