# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='message',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rmessage.proto\x12\x07message\"\x1e\n\rSelectedState\x12\r\n\x05state\x18\x01 \x01(\x0c\" \n\rEmptyResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x81\x01\n\x0eSelectedStates\x12\r\n\x05state\x18\x01 \x01(\x0c\x12\x0f\n\x07setting\x18\x02 \x01(\t\x12\x0f\n\x07weights\x18\x03 \x01(\x0c\x12\x14\n\x0c\x63luster_dict\x18\x04 \x01(\x0c\x12\x13\n\x0b\x64\x65vice_dict\x18\x05 \x01(\x0c\x12\x13\n\x0bupdate_dict\x18\x06 \x01(\x0c\"\x1c\n\x0bGlobalState\x12\r\n\x05state\x18\x01 \x01(\x0c\"@\n\x14RequestRandomIndices\x12\x13\n\x0bnum_clients\x18\x01 \x01(\x05\x12\x13\n\x0bnum_samples\x18\x02 \x01(\x05\"/\n\x15ResponseRandomIndices\x12\x16\n\x0e\x64\x65vice_indices\x18\x01 \x03(\x05\x32\xe1\x01\n\x0bgrpcService\x12<\n\tsendState\x12\x17.message.SelectedStates\x1a\x14.message.GlobalState\"\x00\x12\x43\n\x0fsendSingleState\x12\x16.message.SelectedState\x1a\x16.message.EmptyResponse\"\x00\x12O\n\x0crandomSample\x12\x1d.message.RequestRandomIndices\x1a\x1e.message.ResponseRandomIndices\"\x00\x62\x06proto3'
)




_SELECTEDSTATE = _descriptor.Descriptor(
  name='SelectedState',
  full_name='message.SelectedState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='message.SelectedState.state', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=56,
)


_EMPTYRESPONSE = _descriptor.Descriptor(
  name='EmptyResponse',
  full_name='message.EmptyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='message.EmptyResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=90,
)


_SELECTEDSTATES = _descriptor.Descriptor(
  name='SelectedStates',
  full_name='message.SelectedStates',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='message.SelectedStates.state', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='setting', full_name='message.SelectedStates.setting', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='weights', full_name='message.SelectedStates.weights', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cluster_dict', full_name='message.SelectedStates.cluster_dict', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='device_dict', full_name='message.SelectedStates.device_dict', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='update_dict', full_name='message.SelectedStates.update_dict', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=222,
)


_GLOBALSTATE = _descriptor.Descriptor(
  name='GlobalState',
  full_name='message.GlobalState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='message.GlobalState.state', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=252,
)


_REQUESTRANDOMINDICES = _descriptor.Descriptor(
  name='RequestRandomIndices',
  full_name='message.RequestRandomIndices',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_clients', full_name='message.RequestRandomIndices.num_clients', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_samples', full_name='message.RequestRandomIndices.num_samples', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=254,
  serialized_end=318,
)


_RESPONSERANDOMINDICES = _descriptor.Descriptor(
  name='ResponseRandomIndices',
  full_name='message.ResponseRandomIndices',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_indices', full_name='message.ResponseRandomIndices.device_indices', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=320,
  serialized_end=367,
)

DESCRIPTOR.message_types_by_name['SelectedState'] = _SELECTEDSTATE
DESCRIPTOR.message_types_by_name['EmptyResponse'] = _EMPTYRESPONSE
DESCRIPTOR.message_types_by_name['SelectedStates'] = _SELECTEDSTATES
DESCRIPTOR.message_types_by_name['GlobalState'] = _GLOBALSTATE
DESCRIPTOR.message_types_by_name['RequestRandomIndices'] = _REQUESTRANDOMINDICES
DESCRIPTOR.message_types_by_name['ResponseRandomIndices'] = _RESPONSERANDOMINDICES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SelectedState = _reflection.GeneratedProtocolMessageType('SelectedState', (_message.Message,), {
  'DESCRIPTOR' : _SELECTEDSTATE,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:message.SelectedState)
  })
_sym_db.RegisterMessage(SelectedState)

EmptyResponse = _reflection.GeneratedProtocolMessageType('EmptyResponse', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYRESPONSE,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:message.EmptyResponse)
  })
_sym_db.RegisterMessage(EmptyResponse)

SelectedStates = _reflection.GeneratedProtocolMessageType('SelectedStates', (_message.Message,), {
  'DESCRIPTOR' : _SELECTEDSTATES,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:message.SelectedStates)
  })
_sym_db.RegisterMessage(SelectedStates)

GlobalState = _reflection.GeneratedProtocolMessageType('GlobalState', (_message.Message,), {
  'DESCRIPTOR' : _GLOBALSTATE,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:message.GlobalState)
  })
_sym_db.RegisterMessage(GlobalState)

RequestRandomIndices = _reflection.GeneratedProtocolMessageType('RequestRandomIndices', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTRANDOMINDICES,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:message.RequestRandomIndices)
  })
_sym_db.RegisterMessage(RequestRandomIndices)

ResponseRandomIndices = _reflection.GeneratedProtocolMessageType('ResponseRandomIndices', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSERANDOMINDICES,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:message.ResponseRandomIndices)
  })
_sym_db.RegisterMessage(ResponseRandomIndices)



_GRPCSERVICE = _descriptor.ServiceDescriptor(
  name='grpcService',
  full_name='message.grpcService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=370,
  serialized_end=595,
  methods=[
  _descriptor.MethodDescriptor(
    name='sendState',
    full_name='message.grpcService.sendState',
    index=0,
    containing_service=None,
    input_type=_SELECTEDSTATES,
    output_type=_GLOBALSTATE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='sendSingleState',
    full_name='message.grpcService.sendSingleState',
    index=1,
    containing_service=None,
    input_type=_SELECTEDSTATE,
    output_type=_EMPTYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='randomSample',
    full_name='message.grpcService.randomSample',
    index=2,
    containing_service=None,
    input_type=_REQUESTRANDOMINDICES,
    output_type=_RESPONSERANDOMINDICES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GRPCSERVICE)

DESCRIPTOR.services_by_name['grpcService'] = _GRPCSERVICE

# @@protoc_insertion_point(module_scope)
